# Generated by Django 4.2.7 on 2023-12-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=17)),
                ('title_for_req', models.CharField(max_length=30)),
                ('skillsets', models.CharField(max_length=20)),
                ('must_have', models.CharField(max_length=30)),
                ('good_to_have', models.DateField()),
                ('exp_range_min', models.DateField()),
                ('max', models.CharField(max_length=17)),
                ('budget_min', models.IntegerField()),
                ('budget_max', models.CharField(max_length=17)),
                ('positions', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=20)),
                ('hire_type', models.CharField(max_length=20)),
                ('work_type', models.CharField(max_length=20)),
                ('recruiter', models.EmailField(max_length=254)),
                ('account_mgr', models.CharField(max_length=20)),
            ],
        ),
    ]
