# Generated by Django 4.2.7 on 2023-12-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_priority_alter_user_account_mgr_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Student',
        ),
    ]
