# Generated by Django 3.2.23 on 2023-12-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_add_requirement_budget_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_requirement',
            name='account_mgr',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='budget_min',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='client',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='exp_range_min',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='good_to_have',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='hire_type',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='location',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='max',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='must_have',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='skillsets',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='title_for_req',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='work_type',
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Department',
            field=models.CharField(default='Department', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Email_Id',
            field=models.CharField(default='Email_Id', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='First_Name',
            field=models.CharField(default='First_Name', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Job_Title',
            field=models.CharField(default='Job_Title', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Last_Name',
            field=models.CharField(default='Last_Name', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Linkedin',
            field=models.CharField(default='Linkedin', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Mobile_No',
            field=models.CharField(default='Mobile_No', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Select_City',
            field=models.CharField(default='Select_City', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Select_Company',
            field=models.CharField(default='Select_Company', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Select_Country',
            field=models.CharField(default='Select_Country', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Select_Source',
            field=models.CharField(default='Select_Source', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Select_State',
            field=models.CharField(default='Select_State', max_length=255),
        ),
    ]
