# Generated by Django 4.2.7 on 2023-12-07 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_user_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Add_requirement',
        ),
    ]
