# Generated by Django 4.2.7 on 2023-12-07 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_add_requirement_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Add_requirement',
        ),
    ]
