# Generated by Django 4.2.7 on 2023-12-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_students_add_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_requirement',
            name='budget_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='add_requirement',
            name='budget_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='add_requirement',
            name='exp_range_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='add_requirement',
            name='max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='add_requirement',
            name='positions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='add_requirement',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
