# Generated by Django 4.2.7 on 2023-12-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_add_requirement_budget_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_requirement',
            name='account_mgr',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='budget_min',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='exp_range_min',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='good_to_have',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='hire_type',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='max',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='must_have',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='skillsets',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='title_for_req',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='work_type',
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='accountmgr',
            field=models.CharField(default='accountmgr', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='candidatename',
            field=models.CharField(default='candidatename', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='currentcompany',
            field=models.CharField(default='currentcompany', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='currentctc',
            field=models.CharField(default='currentctc', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='emailid',
            field=models.CharField(default='emailid', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='expectedctc',
            field=models.CharField(default='expectedctc', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='hiretype',
            field=models.CharField(default='hiretype', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='locationpreference',
            field=models.CharField(default='locationpreference', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='mobileno',
            field=models.CharField(default='mobileno', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='noticeperiod',
            field=models.CharField(default='noticeperiod', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='position',
            field=models.CharField(default='position', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='requirement',
            field=models.CharField(default='requirement', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='selAccmanager',
            field=models.CharField(default='selAccmanager', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='worktype',
            field=models.CharField(default='worktype', max_length=255),
        ),
        migrations.AlterField(
            model_name='add_requirement',
            name='client',
            field=models.CharField(default='client', max_length=255),
        ),
        migrations.AlterField(
            model_name='add_requirement',
            name='contact',
            field=models.CharField(default='contact', max_length=255),
        ),
        migrations.AlterField(
            model_name='add_requirement',
            name='location',
            field=models.CharField(default='location', max_length=255),
        ),
        migrations.AlterField(
            model_name='add_requirement',
            name='recruiter',
            field=models.CharField(default='recruiter', max_length=255),
        ),
    ]
