# Generated by Django 3.2.23 on 2023-12-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_add_requirement_budget_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_requirement',
            name='account_mgr',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='budget_max',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='budget_min',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='client',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='exp_range_min',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='good_to_have',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='hire_type',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='location',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='max',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='must_have',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='skillsets',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='title_for_req',
        ),
        migrations.RemoveField(
            model_name='add_requirement',
            name='work_type',
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Address_1',
            field=models.CharField(default='Address_1', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Address_2',
            field=models.CharField(default='Address_2', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='COMPANY_NAME',
            field=models.CharField(default='COMPANY_NAME', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='City',
            field=models.CharField(default='City', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Company_Size',
            field=models.CharField(default='Company_Size', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Country',
            field=models.CharField(default='Country', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Industry',
            field=models.CharField(default='Industry', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Linkedin',
            field=models.CharField(default='Linkedin', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Networth',
            field=models.CharField(default='Networth', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='State',
            field=models.CharField(default='State', max_length=255),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='URL',
            field=models.URLField(default='URL'),
        ),
        migrations.AddField(
            model_name='add_requirement',
            name='Zip',
            field=models.CharField(default='Zip', max_length=255),
        ),
    ]
